openapi: 3.0.3
info:
  title: ServiceNow Incident Plugin
  description: A plugin that retrieves incident information and can create incidents in ServiceNow.
  version: 1.0.0
servers:
  - url: http://localhost:5003
paths:
  /get-incident:
    post:
      operationId: submitIncident
      summary: Retrieve incident information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetIncidentRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncidentResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    GetIncidentRequest:
      type: object
      properties:
        service_now_uri:
          type: string
          description: The ServiceNow URI, it should be in this format https://rydersystemsdev.service-now.com
        username:
          type: string
          description: The API username for authentication.
        password:
          type: string
          description: The API password for authentication.
        incident_number:
          type: string
          description: The number of the incident to retrieve.
    IncidentResponse:
      type: object
      properties:
        incident_number:
          type: string
          description: The incident number.
        short_description:
          type: string
          description: A brief description of the incident.
        status:
          type: string
          description: The status of the incident.
        assigned_to:
          type: string
          description: The person or group assigned to the incident.
        work_notes:
          type: array
          items:
            type: string
          description: The work notes related to the incident, provide a detailed summary.
        comments:
          type: array
          items:
            type: string
          description: The comments related to the incident, provide a detailed summary.
        Pinecone Recommendations:
          type: array
          items:
            type: string
          description: The recommendations for the incident from Pinecone.
        AI Recommendations:
          type: string
          description: The AI's recommended solution for the incident.
    Error:
      type: object
      properties:
        error:
          type: string
          description: The error message.
