openapi: 3.0.3
info:
  title: ServiceNow Incident Plugin
  description: A plugin that retrieves incident information and can create incidents in ServiceNow.
  version: 1.0.0
servers:
  - url: http://localhost:5003
paths:
  /create-service-request:
    post:
      operationId: createServiceRequest
      summary: Create a service request in ServiceNow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateServiceRequestRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateServiceRequestResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /get-incident:
    post:
      operationId: submitIncident
      summary: Retrieve general incident information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetIncidentRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncidentResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /get_assigned_to_user:
    post:
      operationId: getIncidentsByUser
      summary: Retrieve incidents assigned to a particular user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetIncidentsByUserRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncidentsByUserResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /generate-recommendation:
    post:
      operationId: generateRecommendation
      summary: Generate a recommendation on how to solve an incident
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateRecommendationRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateRecommendationResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /get-sla-time:
    post:
      operationId: getSLATime
      summary: Get SLA time for an incident
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetSLATimeRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSLATimeResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
/check-licensing-consumption:
    get:
      operationId: checkLicensingConsumption
      summary: Check licensing consumption
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicensingConsumptionResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    CreateServiceRequestRequest:
      type: object
      properties:
        short_description:
          type: string
          description: A brief description of the service request.
        description:
          type: string
          description: The detailed description of the service request.
    CreateServiceRequestResponse:
      type: object
      properties:
        result:
          type: object
          description: The created service request information.
    GetIncidentRequest:
      type: object
      properties:
        incident_number:
          type: string
          description: The number of the incident to retrieve.
    GetIncidentsByUserRequest:
      type: object
      properties:
        assigned_to:
          type: string
          description: The user to retrieve incidents for the user.
    GenerateRecommendationRequest:
      type: object
      properties:
        incident_number:
          type: string
          description: The number of the incident to generate a recommendation for.
        description:
          type: string
          description: The description of the incident.
        work_notes:
          type: array
          items:
            type: string
          description: The work notes related to the incident.
        comments:
          type: array
          items:
            type: string
          description: The comments related to the incident.
        relevantinfo:
          type: array
          items:
            type: string
          description: The relevant incident details.
    IncidentResponse:
      type: object
      properties:
        incident_number:
          type: string
          description: The incident number.
        short_description:
          type: string
          description: A brief description of the incident.
        status:
          type: string
          description: The status of the incident.
        assigned_to:
          type: string
          description: The person or group assigned to the incident.
        work_notes:
          type: array
          items:
            type: string
          description: The work notes related to the incident, provide a detailed summary.
        comments:
          type: array
          items:
            type: string
          description: The comments related to the incident, provide a detailed summary.
    IncidentsByUserResponse:
      type: object
      properties:
        incident_count:
          type: integer
          description: The count of incidents assigned to the user.
        incidents:
          type: array
          items:
            $ref: '#/components/schemas/IncidentResponse'
    GenerateRecommendationResponse:
      type: object
      properties:
        recommendation:
          type: string
          description: The generated recommendation.
    GetSLATimeRequest:
      type: object
      properties:
        service_now_uri:
          type: string
          description: The ServiceNow URI.
        username:
          type: string
          description: The username for authentication.
        password:
          type: string
          description: The password for authentication.
        incident_number:
          type: string
          description: The number of the incident to retrieve the SLA time for.
    GetSLATimeResponse:
      type: object
      properties:
        sla_time:
          type: string
          description: The SLA time for the incident.
    LicensingConsumptionResponse:
      type: array
      items:
        type: object
        properties:
          application_name:
            type: string
            description: The name of the application.
          total_license_units:
            type: integer
            description: The total license units.
          used_license_units:
            type: integer
            description: The used license units.
    Error:
      type: object
      properties:
        error:
          type: string
          description: The error message.
